name: Backup Leads to GitHub

on:
  schedule:
    - cron: "0 */3 * * *"    # every 3 hours
  workflow_dispatch:          # allows manual trigger

permissions:
  contents: write   # <-- this allows the bot to push commits
  
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ ensures push works

      - name: Fetch leads from Render
        run: |
          mkdir -p backups
          curl -s https://json-server-n815.onrender.com/leads > backups/leads.json

      - name: Commit and push backup
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add backups/leads.json
          git commit -m "Backup leads $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
